spring:
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: oauth
jwt:
  secret: asd
url:
  redirect: /auth/login/s
